export type Item = (typeof items)[number];

export type Region = (typeof regions)[number];

export const regions = [
  { id: 1, name: 'Ash Canyon', imageSrc: '/regions/low-quality/ash-canyon.webp' },
  { id: 2, name: 'Blackrock', imageSrc: '/regions/low-quality/blackrock.webp' },
  { id: 3, name: 'Bleak Inlet', imageSrc: '/regions/low-quality/bleak-inlet.webp' },
  { id: 4, name: 'Broken Railroad', imageSrc: '/regions/low-quality/broken-railroad.webp' },
  { id: 5, name: 'Coastal Highway', imageSrc: '/regions/low-quality/coastal-highway.webp' },
  { id: 6, name: 'Desolation Point', imageSrc: '/regions/low-quality/desolation-point.webp' },
  { id: 7, name: 'Far Range Branch Line', imageSrc: '/regions/low-quality/far-range-branch-line.webp' },
  { id: 8, name: 'Forlorn Muskeg', imageSrc: '/regions/low-quality/forlorn-muskeg.webp' },
  { id: 9, name: 'Hushed River Valley', imageSrc: '/regions/low-quality/hushed-river-valley.webp' },
  { id: 10, name: 'Mountain Town', imageSrc: '/regions/low-quality/mountain-town.webp' },
  { id: 11, name: 'Mystery Lake', imageSrc: '/regions/low-quality/mystery-lake.webp' },
  { id: 12, name: 'Plesant Valley', imageSrc: '/regions/low-quality/plesant-walley.webp' },
  { id: 13, name: 'Timberwolf Mountain', imageSrc: '/regions/low-quality/timberwolf-mountain.webp' },
  { id: 14, name: 'Transfer Pass', imageSrc: '/regions/low-quality/transfer-pass.webp' },
];

export const items = [
  { id: 1, name: 'Arrow_shaft', path: '/items/low-quality/Arrow_shaft_icon.webp' },
  { id: 2, name: 'Green_Maple_Sapling', path: '/items/low-quality/Green_Maple_Sapling_icon.webp' },
  { id: 3, name: 'Reclaimed_wood', path: '/items/low-quality/Reclaimed_wood_icon.webp' },
  { id: 4, name: 'Arrowhead', path: '/items/low-quality/Arrowhead_icon.webp' },
  { id: 5, name: 'Gut', path: '/items/low-quality/Gut_icon.webp' },
  { id: 6, name: 'Reishi_mushroom', path: '/items/low-quality/Reishi_mushroom_icon.webp' },
  { id: 7, name: 'Barbs_Rifle', path: '/items/low-quality/Barbs_Rifle_icon.webp' },
  { id: 8, name: 'Hacksaw', path: '/items/low-quality/Hacksaw_icon.webp' },
  { id: 9, name: 'Revolver_Ammunition', path: '/items/low-quality/Revolver_Ammunition_icon.webp' },
  { id: 10, name: 'Bear_skin_bedroll', path: '/items/low-quality/Bear_skin_bedroll_icon.webp' },
  { id: 11, name: 'Heavy_hammer', path: '/items/low-quality/Heavy_hammer_icon.webp' },
  { id: 12, name: 'Revolver_Shell_Casing', path: '/items/low-quality/Revolver_Shell_Casing_icon.webp' },
  { id: 13, name: 'Bedroll', path: '/items/low-quality/Bedroll_icon.webp' },
  { id: 14, name: 'Hook', path: '/items/low-quality/Hook_icon.webp' },
  { id: 15, name: 'Revolver', path: '/items/low-quality/Revolver_icon.webp' },
  { id: 16, name: 'Birch_bark', path: '/items/low-quality/Birch_bark_icon.webp' },
  { id: 17, name: 'Hunting_rifle', path: '/items/low-quality/Hunting_rifle_icon.webp' },
  { id: 18, name: 'Rifle_Shell_Casing', path: '/items/low-quality/Rifle_Shell_Casing_icon.webp' },
  { id: 19, name: 'Black_bear_hide', path: '/items/low-quality/Black_bear_hide_icon.webp' },
  { id: 20, name: 'Improvised_Crampons', path: '/items/low-quality/Improvised_Crampons_icon.webp' },
  { id: 21, name: 'Rifle_ammunition', path: '/items/low-quality/Rifle_ammunition_icon.webp' },
  { id: 22, name: 'Bullet', path: '/items/low-quality/Bullet_icon.webp' },
  { id: 23, name: 'Improvised_hatchet', path: '/items/low-quality/Improvised_hatchet_icon.webp' },
  { id: 24, name: 'Rifle_cleaning_kit', path: '/items/low-quality/Rifle_cleaning_kit_icon.webp' },
  { id: 25, name: 'Can_of_Gunpowder', path: '/items/low-quality/Can_of_Gunpowder_icon.webp' },
  { id: 26, name: 'Improvised_knife', path: '/items/low-quality/Improvised_knife_icon.webp' },
  { id: 27, name: 'Rose_hip', path: '/items/low-quality/Rose_hip_icon.webp' },
  { id: 28, name: 'Car_Battery', path: '/items/low-quality/Car_Battery_icon.webp' },
  { id: 29, name: 'Jerry_can', path: '/items/low-quality/Jerry_can_icon.webp' },
  { id: 30, name: 'Scrap_Lead', path: '/items/low-quality/Scrap_Lead_icon.webp' },
  { id: 31, name: 'Cloth', path: '/items/low-quality/Cloth_icon.webp' },
  { id: 32, name: 'Line', path: '/items/low-quality/Line_icon.webp' },
  { id: 33, name: 'Scrap_metal', path: '/items/low-quality/Scrap_metal_icon.webp' },
  { id: 34, name: 'Crow_feather', path: '/items/low-quality/Crow_feather_icon.webp' },
  { id: 35, name: 'Magnifying_lens', path: '/items/low-quality/Magnifying_lens_icon.webp' },
  { id: 36, name: 'Sewing_kit', path: '/items/low-quality/Sewing_kit_icon.webp' },
  { id: 37, name: 'Curators_Rifle', path: '/items/low-quality/Curators_Rifle_icon.webp' },
  { id: 38, name: 'Marine_Flare', path: '/items/low-quality/Marine_Flare_icon.webp' },
  { id: 39, name: 'Simple_arrow', path: '/items/low-quality/Simple_arrow_icon.webp' },
  { id: 40, name: 'Cured_Maple_Sapling', path: '/items/low-quality/Cured_Maple_Sapling_icon.webp' },
  { id: 25, name: 'Moose_hide', path: '/items/low-quality/Moose_hide_icon.webp' },
  { id: 25, name: 'Spray_Paint', path: '/items/low-quality/Spray_Paint_icon.webp' },
  { id: 25, name: 'Cured_leather', path: '/items/low-quality/Cured_leather_icon.webp' },
  { id: 25, name: 'Mountaineering_rope', path: '/items/low-quality/Mountaineering_rope_icon.webp' },
  { id: 25, name: 'Stick', path: '/items/low-quality/Stick_icon.webp' },
  { id: 25, name: 'Deer_hide', path: '/items/low-quality/Deer_hide_icon.webp' },
  { id: 25, name: 'Noisemaker', path: '/items/low-quality/Noisemaker_icon.webp' },
  { id: 25, name: 'Storm_lantern', path: '/items/low-quality/Storm_lantern_icon.webp' },
  { id: 25, name: 'Distress_pistol', path: '/items/low-quality/Distress_pistol_icon.webp' },
  { id: 25, name: 'Old_mans_beard_lichen', path: '/items/low-quality/Old_mans_beard_lichen_icon.webp' },
  { id: 25, name: 'Stump_Remover', path: '/items/low-quality/Stump_Remover_icon.webp' },
  { id: 25, name: 'Dusting_Sulfur', path: '/items/low-quality/Dusting_Sulfur_icon.webp' },
  { id: 25, name: 'Prepared_Birch_Bark', path: '/items/low-quality/Prepared_Birch_Bark_icon.webp' },
  { id: 25, name: 'Survival_bow', path: '/items/low-quality/Survival_bow_icon.webp' },
  { id: 25, name: 'Emergency_stim', path: '/items/low-quality/Emergency_stim_icon.webp' },
  { id: 25, name: 'Prepared_reishi_mushrooms', path: '/items/low-quality/Prepared_reishi_mushrooms_icon.webp' },
  { id: 25, name: 'Vaughns_Rifle', path: '/items/low-quality/Vaughns_Rifle_icon.webp' },
  { id: 25, name: 'Firestriker', path: '/items/low-quality/Firestriker_icon.webp' },
  { id: 25, name: 'Prepared_rose_hips', path: '/items/low-quality/Prepared_rose_hips_icon.webp' },
  { id: 25, name: 'Whetstone', path: '/items/low-quality/Whetstone_icon.webp' },
  { id: 25, name: 'Fishing_tackle', path: '/items/low-quality/Fishing_tackle_icon.webp' },
  { id: 25, name: 'Prybar', path: '/items/low-quality/Prybar_icon.webp' },
  { id: 25, name: 'Wolf_pelt', path: '/items/low-quality/Wolf_pelt_icon.webp' },
  { id: 25, name: 'Flare', path: '/items/low-quality/Flare_icon.webp' },
  { id: 25, name: 'Quality_tools', path: '/items/low-quality/Quality_tools_icon.webp' },
  { id: 25, name: 'Wood_matches', path: '/items/low-quality/Wood_matches_icon.webp' },
  { id: 25, name: 'Flare_shell', path: '/items/low-quality/Flare_shell_icon.webp' },
  { id: 25, name: 'Rabbit_pelt', path: '/items/low-quality/Rabbit_pelt_icon.webp' },
  { id: 25, name: 'Woodwrights_Bow', path: '/items/low-quality/Woodwrights_Bow_icon.webp' },
];

export const saveItem = (region: any) => console.log('saving region', region);
